name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Type checking
        run: yarn run check-types

      - name: Type checking
        run: yarn run check-types

      - name: Build Next.js
        run: yarn run build
        env:
          CI: true

      - name: Lint
        run: yarn lint